### ISSUE TITLE
TypeScript issue

### ISSUE THREAD

**Issue by sangdth** [Fristroop/easypanel.js#1]
My build failed on Nextjs application because of below TypeScript issue.

```
lib/easypanel.ts:3:39 - error TS2345: Argument of type '{ endpoint: string; token: string; }' is not assignable to parameter of type 'ClientConfig'.
  Property 'credentials' is missing in type '{ endpoint: string; token: string; }' but required in type 'ClientConfig'.
```

<img width="1010" alt="Screenshot 2023-11-26 at 16 32 40" src="https://github.com/Fristroop/easypanel.js/assets/1083478/be734bda-c663-4380-b76c-855f729b99c0">

**Comment by AydinTheFirst** [comment]
Hi thank you for using this package in this case just add blank strings for username and password in next relase this bug will be fixed

```js
  credentials: {
    username: "",
    password: "",
  },
```

let me know if you have any other issues.

**Comment by sangdth** [comment]
Hi, thanks for addressing the issue. That way it can silent the TS error.
