### ISSUE TITLE
Support getting service deployments

### ISSUE THREAD

**Issue by JulianHartl** [Fristroop/easypanel.js#4]
In the panel, you can see a list of all deployments and their status, but you cannot fetch them via the package yet.
![Bildschirmfoto 2023-12-01 um 11 03 53](https://github.com/Fristroop/easypanel.js/assets/101909285/bf281be4-3e57-4260-868d-54a04371e3e5)

**Comment by AydinTheFirst** [comment]
https://github.com/Fristroop/easypanel.js/commit/06ba948b00bafd1b1b3b795e9435f1b6d9516311
