### ISSUE TITLE
Small typo in `ServiceType`

### ISSUE THREAD

**Issue by sangdth** [Fristroop/easypanel.js#6]
Hi, thanks for your update. Today I tried this sdk again and it works great!

I found only one small typo still remained:

https://github.com/Fristroop/easypanel.js/blob/22203983e12a0ccf78e8ef4e7323695adde6324f/src/types/general.types.ts#L116

The service type should be `postgres`, I believe.

**Comment by AydinTheFirst** [comment]
Thanks for letting me know

https://github.com/Fristroop/easypanel.js/commit/7457009ded7e40b9db90aafda50268846a26d7d9

**Comment by sangdth** [comment]
thanks for amazing works!
